trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    fetchDepth: 0

  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: "sonarqube"
      organization: "eq09"
      scannerMode: "cli"
      configMode: "manual"
      cliProjectKey: "eq09"
      cliProjectName: "equipe 9"
      cliSources: "."
      extraProperties: |
        sonar.branch.name=main

  - script: echo "build rodando..."
    displayName: "Build"

  - task: SonarCloudAnalyze@3
