trigger:
  - main

pr:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Instalar Node.js"

  - script: npm ci
    displayName: "Instalar dependências"

  - script: npm run test
    displayName: "Executar testes automatizados"
    continueOnError: true

  - task: PublishTestResults@2
    displayName: "Publicar resultado dos testes"
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "test-results/junit.xml"
      failTaskOnFailedTests: true
